name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  haskel_install:
    runs-on: "ubuntu-latest"

    steps:
    - name: Check Haskel version
      run: |
        ghcup --version
        ghc --version
    - name: Install Haskel and Cabal
      run: |
        ghcup install ghc "9.4.7"
        ghcup install cabal "3.6.2.1"
    - name: Check Haskel version
      run: ghc --version
    - name: Check Cabal version
      run: cabal --version

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: haskell-install
    - uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
